[package]
name = "mannager"
version = "0.1.0"
edition = "2021"

[dependencies]
decompress = "0.6.0"
iced = {version = "0.13.1", features = ["svg", "tokio"]}
reqwest = "0.12.7"
rfd = "0.15.0"
tokio = {version = "1.40.0", features = ["full"]}
