[package]
name = "mannager"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0.33"
iced = {version = "0.13.1", features = ["svg", "tokio", "multi-window"]}
iced_aw = { version = "0.11.0", features = ["number_input", "menu"] }
notify-rust = "4.11.3"
open = "5.3.0"
pty-process = {version = "0.4.0", features = ["async"]}
reqwest = "0.12.7"
rfd = "0.15.0"
scraper = "0.20.0"
serde = "1.0.210"
tar = "0.4.42"
thiserror = "1.0.64"
tokio = {version = "1.40.0", features = ["full"]}
toml = "0.8.19"
zip = { version = "2.2.0", features = ["deflate-flate2"] }
