module = "icon"

[icons]
book = "book-open-text"
bug = "bug"
check = "check"
left_arrow = "chevron-left"
right_arrow = "chevron-right"
up_arrow = "chevron-up"
down_arrow = "chevron-down"
warning = "circle-alert"
copy = "copy"
download = "download"
port = "ethernet-port"
folder = "folder"
password = "key-round"
link = "link"
map = "map-pinned"
menu = "menu"
minus = "minus"
plus = "plus"
edit = "pencil"
start = "play"
stop = "square"
terminal = "terminal"
trash = "trash-2"
users = "users"
close = "x"
