name: Deploy to GitHub Releases

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            exe: mannager.exe
          - os: ubuntu-latest
            exe: mannager

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from Cargo.toml
        id: get-version
        shell: bash
        run: echo "version=$(grep '^version' Cargo.toml | head -1 | sed 's/version = \"//;s/\"//')" >> $GITHUB_OUTPUT

      - name: Cache Rust build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build
        run: cargo build --release

      - name: Stage release files
        shell: bash
        run: |
          mkdir staging
          cp target/release/${{ matrix.exe }} staging/

      - name: Install vpk
        run: dotnet tool install -g vpk

      - name: Pack
        shell: bash
        run: |
          mkdir Releases

          vpk pack \
            -u net.tsuza.mannager \
            -v ${{ steps.get-version.outputs.version }} \
            -p staging \
            -o ./Releases
            -e ${{ matrix.exe }}
            --packTitle mannager
            --packAuthors "tsuza"
            --icon assets/app_icon.png
            --releaseNotes CHANGELOG.md

      - name: Upload
        shell: bash
        run: |
          vpk upload github \
            --repoUrl https://github.com/${{ github.repository }} \
            --publish \
            --releaseName "v${{ steps.get-version.outputs.version }}" \
            --tag v${{ steps.get-version.outputs.version }} \
            --token ${{ secrets.GITHUB_TOKEN }}
